name: argus
channels:
  - defaults
dependencies:
  - python=3.8
  - ca-certificates=2023.08.22
  - libffi=3.4.4
  - openssl=3.0.11
  - pip=23.2.1
  - python=3.8.18
  - setuptools=68.0.0
  - sqlite=3.41.2
  - wheel=0.38.4
  - pip:
    - asgiref==3.7.2
    - astropy==5.2.2
    - backports-zoneinfo==0.2.1
    - bidict==0.22.1
    - certifi==2023.7.22
    - cffi==1.15.1
    - charset-normalizer==3.2.0
    - cryptography==41.0.4
    - defusedxml==0.7.1
    - dj-rest-auth==5.0.1
    - django==4.2.5
    - django-allauth==0.56.1
    - djangorestframework==3.14.0
    - dnspython==2.4.2
    - ephem==4.1.4
    - eventlet==0.33.3
    - greenlet==3.0.0
    - h11==0.14.0
    - idna==3.4
    - numpy==1.24.4
    - oauthlib==3.2.2
    - packaging==23.1
    - pandas==2.0.3
    - pycparser==2.21
    - pyerfa==2.0.0.3
    - pyjwt==2.8.0
    - python-dateutil==2.8.2
    - python-engineio==4.7.1
    - python-socketio==5.9.0
    - python3-openid==3.2.0
    - pytz==2023.3.post1
    - pyyaml==6.0.1
    - requests==2.31.0
    - requests-oauthlib==1.3.1
    - simple-websocket==1.0.0
    - six==1.16.0
    - sqlparse==0.4.4
    - typing-extensions==4.8.0
    - tzdata==2023.3
    - urllib3==2.0.5
    - wsproto==1.2.0
