# Generated by Django 4.2.5 on 2023-10-09 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telescope',
            fields=[
                ('name', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('status', models.CharField(default='idle', max_length=16)),
                ('ra', models.FloatField(null=True)),
                ('dec', models.FloatField(null=True)),
                ('alt', models.FloatField(null=True)),
                ('az', models.FloatField(null=True)),
                ('operation', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='observationplan',
            name='end_time',
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.observationplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
