# Generated by Django 4.2.5 on 2023-10-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_telescope_remove_observationplan_end_time_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='observationplan',
            name='filters',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='observationplan',
            name='reduction',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
