# Generated by Django 4.2.5 on 2023-10-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_observationplan_filters_observationplan_reduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='observationplan',
            name='exptime',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
