# Generated by Django 4.2.5 on 2023-10-19 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_observationplan_exptime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observationplan',
            old_name='reduction',
            new_name='framemode',
        ),
        migrations.AddField(
            model_name='observationplan',
            name='executed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='observationplan',
            name='executed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='observationplan',
            name='outputs',
            field=models.TextField(null=True),
        ),
    ]
