# Generated by Django 4.2.5 on 2023-10-19 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_reduction_observationplan_framemode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telescope',
            name='executing_plan_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
