# Generated by Django 4.2.5 on 2023-11-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_telescope_executing_plan_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observationsmade',
            name='user',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='user',
        ),
        migrations.AddField(
            model_name='telescope',
            name='executing_plan_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='observationplan',
            name='exptime',
            field=models.FloatField(),
        ),
        migrations.DeleteModel(
            name='ObservationSchedule',
        ),
        migrations.DeleteModel(
            name='ObservationsMade',
        ),
        migrations.DeleteModel(
            name='Queue',
        ),
    ]
