# Generated by Django 4.2.5 on 2024-10-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_observationsmade_user_remove_queue_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationplan',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
