# Generated by Django 4.2.5 on 2024-11-04 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_alter_observationplan_start_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="observationplan",
            name="object_name",
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name="observationplan",
            name="dec",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="observationplan",
            name="ra",
            field=models.FloatField(null=True),
        ),
    ]
